issues:
  exclude-rules:
    - linters:
        - unparam
      text: always receives|always nil

linters:
  enable:
    - bodyclose
    - unconvert
    - dupl
    - gocyclo
    - gocognit
    - gofmt
    - misspell
    - unparam
    - exportloopref
    - testpackage
