issues:
  exclude-rules:
    - linters:
        - unparam
      text: always receives|always nil

linters:
  enable:
    - bodyclose
    - interfacer
    - unconvert
    - dupl
    - gocyclo
    - gocognit
    - misspell
    - unparam
    - scopelint
