language: go
go:
  - 1.14.x
  - 1.13.x
os:
  - linux

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y phantomjs
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0

script:
  - make

jobs:
  include:
    - stage: publish test coverage to coveralls.io
      script:
        - go get github.com/mattn/goveralls@v0.0.5
        - $(go env GOPATH)/bin/goveralls -service=travis-ci -ignore=mocks/*.go
    - stage: release to dockerhub
      if: branch = master
      sudo: required
      services:
        - docker
      before_install: []
      install: []
      script:
        - docker build -t $DOCKER_REPO .
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - docker push $DOCKER_REPO

notifications:
  slack:
    secure: WMwdjMgYRtLlbZMmj+Eo75o7Hpb5+MN1hId+EhX0iMN839As0q9N39o/RUJrHCUcrioMvUJptTUpo1BKRb6kIu0GlOJHJPPykMQTc/lHKLe6xgj/0PtSOKmOvctbr2cptgoB9vagZPx69QdKFDlgQT2AGYJtsgbGnU7ipZDApynYJ+C6Wox1xSBUebhbDP+y6q/aH5hH6B51hU7HWW9fdHl+cYYb4CozsA2zT0v+Lv73F456kCR/sND3LN5585r7CbtVeJ4UpzjrFLEGl8pA7FKCi85mkdpxELbUT+aaYCyHhaQZaNf+ql74oOvt8N0vSXZ5xsBXpqDqr5iphtZb9lPh/HL5xc3K87sVM922WZWhFhB8h6O2B/ba9qvwds2w9DWm4RpSUGsGesvqAqzaQmmzwHbSZFMEFBJVEbCgnO8Mo5faHG92R9/c1JNRT4WVrfox9apG3UUO/ScJ9yJzAb7KVkfmjhhV0kf5huqMB9fRszHmeaIiUc5KUrLJDWd0nKeJ6DQXy+u9/Gmz0BJOw+bch53rOCpHp7LJ5SofAk+kp/CXe9hHGVVUE+aQgGCDo9IIxiTFgdRc5H8oOeSuNPYuX8bNNzTvaq8skZPyGIpfA2nTslyE68RheFWtEJQ9Lj9pK6xh9hkDH+rrz3tCuCJNAtE7Bjtbmuo5uV+eHeQ=
