[github]
duration = "12h"

[[github.projects]]
repo = "go"
user = "golang"

[[twitter.timelines]]
screen_name = "golang"
[twitter.timelines.filter]
patterns = ["is released!", "#golang"]
has_url = true
retweeted = false
lang = "en"
[twitter.timelines.filter.vision]
label = ["cartoon|clip art|artwork"]
[twitter.timelines.action]
retweet = true

[[twitter.searches]]
queries = ["foo", "bar"]
[twitter.searches.filter]
retweeted_threshold = 100
[twitter.searches.action]
retweet = true

[twitter.notification]
[twitter.notification.place]
allow_self = true
users = ["foo"]

[twitter]
duration = "30m"

[db]
driver = "driver"
data_source = "user:password@protocol(address)/dbname?param=value"
vision_table = "table"

[interaction]
duration = "30s"
users = ["foo", "bar"]

[log]
allow_self = true
users = ["foo", "bar"]

[http]
name = "Iwataka"
