[github]
duration = "12h"

[[github.projects]]
repo = "go"
user = "golang"

[[twitter.accounts]]
name = "golang"
[twitter.accounts.filter]
patterns = ["is released!", "#golang"]
has_url = true
retweeted = false
retweeted_threshold = 100
lang = "en"
[twitter.accounts.filter.vision]
label = ["cartoon|clip art|artwork"]
[twitter.accounts.action]
retweet = true

[twitter.notification]
[twitter.notification.place]
allow_self = true
users = ["foo"]

[twitter]
duration = "30m"

[interaction]
duration = "30s"
users = ["foo", "bar"]

[log]
allow_self = true
users = ["foo", "bar"]

[authentication]
consumer_key = "TWITTER_CONSUMER_KEY"
consumer_secret = "TWITTER_CONSUMER_SECRET"
access_token = "TWITTER_ACCESS_TOKEN"
access_token_secret = "TWITTER_ACCESS_TOKEN_SECRET"

[option]
name = "Iwataka"
