version: '2'
services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./mongodb:/data/db
  mybot:
    image: iwataka/mybot
    container_name: mybot
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
    environment:
      - MYBOT_DB_ADDRESS=mongo:27017
      - MYBOT_DB_NAME=mybot
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
