apiVersion: v1
kind: Service
metadata:
  name: mybot
  labels:
    app: mybot
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: mybot-svc
  selector:
    app: mybot

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybot
  labels:
    app: mybot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mybot
  template:
    metadata:
      labels:
        app: mybot
    spec:
      containers:
      - name: mybot
        image: iwataka/mybot
        ports:
        - containerPort: 8080
          name: mybot-svc
        env:
          - name: MYBOT_DB_ADDRESS
            value: "mongo:27017"
          - name: MYBOT_DB_NAME
            value: mybot
          # TODO: investigate why this is needed
          - name: MYBOT_PORT
            value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 27017
    targetPort: mongo-svc
  selector:
    app: mongo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
          name: mongo-svc
        volumeMounts:
        - mountPath: /data/db
          name: mongo-pv
      volumes:
      - name: mongo-pv
        persistentVolumeClaim:
          claimName: mongo-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
