// Automatically generated by MockGen. DO NOT EDIT!
// Source: models/cli.go

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Context interface
type MockContext struct {
	ctrl     *gomock.Controller
	recorder *_MockContextRecorder
}

// Recorder for MockContext (not exported)
type _MockContextRecorder struct {
	mock *MockContext
}

func NewMockContext(ctrl *gomock.Controller) *MockContext {
	mock := &MockContext{ctrl: ctrl}
	mock.recorder = &_MockContextRecorder{mock}
	return mock
}

func (_m *MockContext) EXPECT() *_MockContextRecorder {
	return _m.recorder
}

func (_m *MockContext) String(key string) string {
	ret := _m.ctrl.Call(_m, "String", key)
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockContextRecorder) String(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "String", arg0)
}

func (_m *MockContext) Bool(key string) bool {
	ret := _m.ctrl.Call(_m, "Bool", key)
	ret0, _ := ret[0].(bool)
	return ret0
}

func (_mr *_MockContextRecorder) Bool(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Bool", arg0)
}
