// Code generated by MockGen. DO NOT EDIT.
// Source: utils/utils.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockSavable is a mock of Savable interface
type MockSavable struct {
	ctrl     *gomock.Controller
	recorder *MockSavableMockRecorder
}

// MockSavableMockRecorder is the mock recorder for MockSavable
type MockSavableMockRecorder struct {
	mock *MockSavable
}

// NewMockSavable creates a new mock instance
func NewMockSavable(ctrl *gomock.Controller) *MockSavable {
	mock := &MockSavable{ctrl: ctrl}
	mock.recorder = &MockSavableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSavable) EXPECT() *MockSavableMockRecorder {
	return m.recorder
}

// Save mocks base method
func (m *MockSavable) Save() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save")
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save
func (mr *MockSavableMockRecorder) Save() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSavable)(nil).Save))
}

// MockLoadable is a mock of Loadable interface
type MockLoadable struct {
	ctrl     *gomock.Controller
	recorder *MockLoadableMockRecorder
}

// MockLoadableMockRecorder is the mock recorder for MockLoadable
type MockLoadableMockRecorder struct {
	mock *MockLoadable
}

// NewMockLoadable creates a new mock instance
func NewMockLoadable(ctrl *gomock.Controller) *MockLoadable {
	mock := &MockLoadable{ctrl: ctrl}
	mock.recorder = &MockLoadableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLoadable) EXPECT() *MockLoadableMockRecorder {
	return m.recorder
}

// Load mocks base method
func (m *MockLoadable) Load() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(error)
	return ret0
}

// Load indicates an expected call of Load
func (mr *MockLoadableMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockLoadable)(nil).Load))
}

// MockDeletable is a mock of Deletable interface
type MockDeletable struct {
	ctrl     *gomock.Controller
	recorder *MockDeletableMockRecorder
}

// MockDeletableMockRecorder is the mock recorder for MockDeletable
type MockDeletableMockRecorder struct {
	mock *MockDeletable
}

// NewMockDeletable creates a new mock instance
func NewMockDeletable(ctrl *gomock.Controller) *MockDeletable {
	mock := &MockDeletable{ctrl: ctrl}
	mock.recorder = &MockDeletableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDeletable) EXPECT() *MockDeletableMockRecorder {
	return m.recorder
}

// Delete mocks base method
func (m *MockDeletable) Delete() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete")
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockDeletableMockRecorder) Delete() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeletable)(nil).Delete))
}
