// Automatically generated by MockGen. DO NOT EDIT!
// Source: lib/utils.go

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Savable interface
type MockSavable struct {
	ctrl     *gomock.Controller
	recorder *_MockSavableRecorder
}

// Recorder for MockSavable (not exported)
type _MockSavableRecorder struct {
	mock *MockSavable
}

func NewMockSavable(ctrl *gomock.Controller) *MockSavable {
	mock := &MockSavable{ctrl: ctrl}
	mock.recorder = &_MockSavableRecorder{mock}
	return mock
}

func (_m *MockSavable) EXPECT() *_MockSavableRecorder {
	return _m.recorder
}

func (_m *MockSavable) Save() error {
	ret := _m.ctrl.Call(_m, "Save")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockSavableRecorder) Save() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Save")
}

// Mock of Loadable interface
type MockLoadable struct {
	ctrl     *gomock.Controller
	recorder *_MockLoadableRecorder
}

// Recorder for MockLoadable (not exported)
type _MockLoadableRecorder struct {
	mock *MockLoadable
}

func NewMockLoadable(ctrl *gomock.Controller) *MockLoadable {
	mock := &MockLoadable{ctrl: ctrl}
	mock.recorder = &_MockLoadableRecorder{mock}
	return mock
}

func (_m *MockLoadable) EXPECT() *_MockLoadableRecorder {
	return _m.recorder
}

func (_m *MockLoadable) Load() error {
	ret := _m.ctrl.Call(_m, "Load")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockLoadableRecorder) Load() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Load")
}
