// Automatically generated by MockGen. DO NOT EDIT!
// Source: worker.go

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of WorkerMessageHandler interface
type MockWorkerMessageHandler struct {
	ctrl     *gomock.Controller
	recorder *_MockWorkerMessageHandlerRecorder
}

// Recorder for MockWorkerMessageHandler (not exported)
type _MockWorkerMessageHandlerRecorder struct {
	mock *MockWorkerMessageHandler
}

func NewMockWorkerMessageHandler(ctrl *gomock.Controller) *MockWorkerMessageHandler {
	mock := &MockWorkerMessageHandler{ctrl: ctrl}
	mock.recorder = &_MockWorkerMessageHandlerRecorder{mock}
	return mock
}

func (_m *MockWorkerMessageHandler) EXPECT() *_MockWorkerMessageHandlerRecorder {
	return _m.recorder
}

func (_m *MockWorkerMessageHandler) Handle(msg interface{}) error {
	ret := _m.ctrl.Call(_m, "Handle", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockWorkerMessageHandlerRecorder) Handle(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Handle", arg0)
}
