version: '2'
services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./mongodb:/data/db

  mybot_with_mongo:
    image: iwataka/mybot
    container_name: mybot_with_mongo
    # volumes:
    #   - ~/.cache/mybot:/root/.cache/mybot
    #   - ~/.config/mybot:/root/.config/mybot
    #   - ~/.config/gcloud:/root/.config/gcloud
    environment:
      - MYBOT_DB_ADDRESS=mongo:27017
      - MYBOT_DB_NAME=mybot
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
